// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DAL.DTO.CheckersGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameOptionsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GameOverAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameWonByPlayer")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerOneColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerOneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerTwoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameOptionsId");

                    b.HasIndex("PlayerOneId");

                    b.HasIndex("PlayerTwoId");

                    b.ToTable("CheckersGames");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGameOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompulsoryJumps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerOneStarts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameOptions");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckersGameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerOneIsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedBoardState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedNextMoves")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckersGameId");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("DAL.DTO.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGame", b =>
                {
                    b.HasOne("DAL.DTO.CheckersGameOptions", "GameOptions")
                        .WithMany("CheckersGames")
                        .HasForeignKey("GameOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.DTO.Player", "PlayerOne")
                        .WithMany("GamesAsPlayerOne")
                        .HasForeignKey("PlayerOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.DTO.Player", "PlayerTwo")
                        .WithMany("GamesAsPlayerTwo")
                        .HasForeignKey("PlayerTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameOptions");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerTwo");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGameState", b =>
                {
                    b.HasOne("DAL.DTO.CheckersGame", "CheckersGame")
                        .WithMany("GameStates")
                        .HasForeignKey("CheckersGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckersGame");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGame", b =>
                {
                    b.Navigation("GameStates");
                });

            modelBuilder.Entity("DAL.DTO.CheckersGameOptions", b =>
                {
                    b.Navigation("CheckersGames");
                });

            modelBuilder.Entity("DAL.DTO.Player", b =>
                {
                    b.Navigation("GamesAsPlayerOne");

                    b.Navigation("GamesAsPlayerTwo");
                });
#pragma warning restore 612, 618
        }
    }
}
